# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfb9ea7195c27b130b23f795ddb79dc4"
name = "cf"
handle = "cf-5"
application_url = "https://forty-board-mj-yorkshire.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-42d2cafa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://forty-board-mj-yorkshire.trycloudflare.com/auth/callback",
  "https://forty-board-mj-yorkshire.trycloudflare.com/auth/shopify/callback",
  "https://forty-board-mj-yorkshire.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
